apiVersion: v1
kind: Pod
metadata:
  name: Ubuntu_env
  labels:
    role: myrole
spec:
  containers:
    - name: ubuntu
      image: ubuntu
      ports:
        - name: ubuntu
          containerPort: 22
          protocol: TCP
      env:
        - name: POD_NAME
          valueForm:
            fieldRef:
              fieldPath: status.podIP

